Seed:
  tty: true
  restart: always
  ports:
  - 9042:9042/tcp
  - 9160:9160/tcp
  labels: 
    io.rancher.container.dns: true
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  volumes:
   - /usr/local/aeris_lib/resources/:/usr/local/aeris_lib/resources
   - /usr/local/aeris_lib/cassandra/:/usr/local/aeris_lib/cassandra
  environment:
    RANCHER_ENABLE: 'true'
    CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    JVMMEM: ${jvmmem}
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/nrt/cassandra
  command: bash /usr/local/apache-cassandra-2.2.4/bin/start-cassandra.sh seed Seed ${seed_scale}
Peer:
  tty: true
  restart: always
  ports:
  - 9042:9042/tcp
  - 9160:9160/tcp
  labels: 
    io.rancher.container.dns: true
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  volumes:
   - /usr/local/aeris_lib/resources/:/usr/local/aeris_lib/resources
  environment:
    RANCHER_ENABLE: 'true'
    CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    JVMMEM: ${jvmmem}
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/nrt/cassandra
  command: bash /usr/local/apache-cassandra-2.2.4/bin/start-cassandra.sh peer Seed ${seed_scale}
